### ISSUE TITLE
Les URL pour "jouer son troll" ne sont plus bonnes

### ISSUE THREAD

**Issue by athimel** [athimel/mh-dla-notifier#18]
Voir : https://play.google.com/store/apps/details?id=org.zoumbox.mh_dla_notifier&reviewId=Z3A6QU9xcFRPRVJXTFFrbUZyYnd6SDB1TkVxdVpZS0VycVJYR1ZyajdYSjRfbFQ5d2xWdGthWlNnaUFDM1BjVWwySEpkLW5MWng2WHh3N1kzLVVuLVh5NTJn 

et : http://www.mountyhall.com/Forum/display_topic_threads.php?ThreadID=2681630#2681630

**Comment by tatamka** [comment]
quelle rapidité !
#ccqmdt
