### ISSUE TITLE
Quand on clique sur « Jouer votre Trõll » dans la notification, il faudrait fermer la notification

### ISSUE THREAD

**Issue by athimel** [athimel/mh-dla-notifier#21]

**Comment by athimel** [comment]
Quelques informations utile pour le développement.

Il existe déjà dans l'application le code qui permet de nettoyer les notifications de l'application (quand on démarre la `MainActivity`) :

```
        Log.d(TAG, "Clear notifications");
        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.cancelAll();
```

L'intent de l'action sur le bouton « Jouer votre Trõll » est créé par : `MhDlaNotifierUtils#GET_PLAY_INTENT`

**Comment by tatamka** [comment]
yo
ça part quand en prod ?

**Comment by athimel** [comment]
C'est dans l'pipe
